#Apache ActiveMQ used to communicate positions threw services 

apiVersion: apps/v1
kind: Deployment
metadata:
  name: fleetman-queue
  namespace: fleetman
  labels:
    app: fleetman-queue
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fleetman-queue
  template:
    metadata:
      labels:
        app: fleetman-queue
    spec:
      containers:
        - name: fleetman-queue
          image: richardchesterwood/k8s-fleetman-queue:release2
          ports:
          - containerPort: 8161
          - containerPort: 61616
          resources:
            requests:
              memory: "256Mi"
              cpu: "20m"
            limits:
              memory: "512Mi"
              cpu: "50m"
---
apiVersion: v1
kind: Service
metadata:
  name: fleetman-queue
  namespace: fleetman
spec:
  selector:
    app: fleetman-queue
  ports:
    - protocol: TCP
      port: 8161
      targetPort: 8161
      name: first-port
    - protocol: TCP
      port: 61616
      targetPort: 61616
      name: second-port
  type: LoadBalancer
---