apiVersion: apps/v1
kind: Deployment
metadata:
  name: fleetman-api-gateaway
  namespace: fleetman
  labels:
    app: fleetman-api-gateaway
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fleetman-api-gateaway
  template:
    metadata:
      labels:
        app: fleetman-api-gateaway
    spec:
      containers:
        - name: fleetman-api-gateaway
          image: supinfo4kube/api-gateway:1.0.1
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: local-microservice
          resources:
            requests:
              memory: "256Mi"
              cpu: "20m"
            limits:
              memory: "512Mi"
              cpu: "50m"
---
apiVersion: v1
kind: Service
metadata:
  name: fleetman-api-gateaway
  namespace: fleetman
spec:
  selector:
    app: fleetman-api-gateaway
  ports:
    - protocol: TCP
      port: 30020
      targetPort: 8080
      name: http
  type: ClusterIP
