apiVersion: apps/v1
kind: Deployment
metadata:
  name: fleetman-position-simulator
  namespace: fleetman
  labels:
    app: fleetman-fleetman-position-simulator
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fleetman-position-simulator
  template:
    metadata:
      labels:
        app: fleetman-position-simulator
    spec:
      containers:
        - name: fleetman-position-simulator
          image: richardchesterwood/k8s-fleetman-position-simulator:release2
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: local-microservice
          resources:
            requests:
              memory: "256Mi"
              cpu: "20m"
            limits:
              memory: "512Mi"
              cpu: "50m"
---
apiVersion: v1
kind: Service
metadata:
  name: fleetman-position-simulator
  namespace: fleetman
spec:
  selector:
    app: fleetman-position-simulator
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: http
  type: ClusterIP